version: '3.8'

# setup the network
networks:
  frontend:
    external: true
    name: reverse-proxy
  backend:
    driver: bridge

services:

  wordpress:
    depends_on:
      - mysql
    build: ./build/wordpress
    user: "${UID}:${GID}"
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WP_TITLE: ${WP_TITLE}
      WP_ADMIN_USER: ${WP_ADMIN_USER}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
      WP_DEBUG: ${WP_DEBUG}
      WP_URL: ${DOMAIN}
    volumes:
      - ./scripts:/scripts
      - ./data/wordpress:/var/www/html
    # add the network to the service configuration
    networks:
      - frontend
      - backend
    # add the labels to the service configuration
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=reverse-proxy"
      # http
      - "traefik.http.routers.wordpress-${SLUG}.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.wordpress-${SLUG}.entrypoints=web"

  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./data/mysql:/imports
      - mysql:/var/lib/mysql
    # add the network to the service configuration
    networks:
      - backend

volumes:
  mysql:
